threads: 8

bootup_timeout_secs: 20
default_test_timeout_secs: 120

sc_tortillas_bootup: 69420
sc_tortillas_finished: 42069

analyze:

# Exit codes
  - name: exit_codes
    scope: 'SYSCALL'
    pattern: 'Syscall::EXIT: called, exit_code: (\d+)'
    mode: exit_codes
    status: FAILED

# Userspace asserts
  - name: userspace_asserts
    scope: 'SYSCALL'
    pattern: 'Syscall::write: (Assertion failed:.*)'
    mode: add_as_error
    status: FAILED

# Locking errors
  - name: lock_logs
    scope: 'LOCK'
    pattern: '(.*)'
    mode: add_as_error

# Command not understood
  - name: command_not_understood
    scope: 'SYSCALL'
    pattern: 'Syscall::write: (Command not understood)'
    mode: add_as_error
    status: FAILED

# Kernel panics
  - name: kernel_panics
    scope: 'KERNEL PANIC'
    pattern: '(.*)'
    mode: add_as_error
    status: PANIC

# Backtraces
  - name: backtrace
    scope: 'BACKTRACE'
    pattern: '(.*)'
    mode: add_as_error_join
