threads: 8

bootup_timeout_secs: 20
default_test_timeout_secs: 120

sc_tortillas_bootup: 69420
sc_tortillas_finished: 42069

parse:

  - name: kernel_panics
    scope: 'ALL'
    pattern: '(KERNEL PANIC:.*)'

  - name: backtrace
    scope: 'BACKTRACE'
    pattern: '(.*)'

  - name: command_not_understood
    scope: 'SYSCALL'
    pattern: 'Syscall::write: (Command not understood)'

  - name: exit_codes
    scope: 'SYSCALL'
    pattern: 'Syscall::EXIT: called, exit_code: (\d+)'

  - name: userspace_asserts
    scope: 'SYSCALL'
    pattern: 'Syscall::write: (Assertion failed:.*)'


analyze:

  - name: kernel_panics
    mode: add_as_error
    status: PANIC

  - name: backtrace
    mode: add_as_error_join

  - name: command_not_understood
    mode: add_as_error
    status: FAILED

  - name: exit_codes
    mode: exit_codes
    status: FAILED

  - name: userspace_asserts
    mode: add_as_error
    status: FAILED
