before_script:
    - ln -fs /usr/share/zoneinfo/Europe/Vienna /etc/localtime
    - apt update -y
    - DEBIAN_FRONTEND=noninteractive apt install -y git cmake gcc g++ qemu-utils qemu-system-x86 python3-yaml

build:
  stage: build
  script:
    - echo "Building newest commit in $CI_COMMIT_BRANCH!"
    - sh setup_cmake.sh
    - cd /tmp/sweb
    - make -j$(nproc)

tortillas:
  stage: test
  script:
    - git clone https://github.com/PaideiaDilemma/Tortillas.git ./tortillas
    - cd tortillas
    - python3 -m tortillas -S ..
