threads: 8

bootup_timeout_secs: 20
default_test_timeout_secs: 120

sc_tortillas_bootup: 69420
sc_tortillas_finished: 42069

parse:

  - scope: 'KERNEL PANIC'
    pattern: '(.*)'
    label: kernel_panics

  - scope: 'BACKTRACE'
    pattern: '(.*)'
    label: backtrace

  - scope: 'LOCK'
    pattern: '(.*)'
    label: lock_logs

  - scope: 'SYSCALL'
    pattern: 'Syscall::write: (Command not understood)'
    label: command_not_understood

  - scope: 'SYSCALL'
    pattern: 'Syscall::EXIT: called, exit_code: (\d+)'
    label: exit_codes

  - scope: 'SYSCALL'
    pattern: 'Syscall::write: (Assertion failed:.*)'
    label: userspace_asserts

  - scope: 'SYSCALL'
    pattern: 'Syscall::write: (?!\s*TORTILLAS EXPECT: )(.*)'
    label: stdout

  - scope: 'SYSCALL'
    pattern: 'Syscall::write: TORTILLAS EXPECT: (.*)'
    label: expect_stdout


analyze:

  - label: lock_logs
    mode: add_as_error

  - label: kernel_panics
    mode: add_as_error
    status: PANIC

  - label: backtrace
    mode: add_as_error_join

  - label: command_not_understood
    mode: add_as_error
    status: FAILED

  - label: exit_codes
    mode: exit_codes
    status: FAILED

  - label: userspace_asserts
    mode: add_as_error
    status: FAILED

  - label: expect_stdout
    mode: expect_stdout
    status: FAILED
