name: Demo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  base:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout Sweb
        uses: actions/checkout@v3
        with:
          repository: IAIK/sweb
          path: sweb

      - name: Install dependencies
        run: |
          sudo apt install -y qemu-utils qemu-system-x86 python3-yaml

      - name: Setup sweb
        run:
          ./setup_sweb.sh $(pwd)/sweb base

      - name: Run tortillas
        run: |
          python3 -m tortillas -S ./sweb

        # Upload logs as test artifacts
        # - uses: actions/upload-artifact@v3
        # if: always()
        # with:
        #   name: test_logs
        #   path: /tmp/sweb/tortillas/**/out.log

      - name: Adding markdown
        if: always()
        run: cat /tmp/sweb/tortillas_summary.md >> $GITHUB_STEP_SUMMARY

  extended:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout Sweb
        uses: actions/checkout@v3
        with:
          repository: IAIK/sweb
          path: sweb

      - name: Install dependencies
        run: |
          sudo apt install -y qemu-utils qemu-system-x86 python3-yaml

      - name: Setup sweb
        run: |
          ./setup_sweb.sh $(pwd) $(pwd)/sweb extended

      - name: Run tortillas
        run: |
          python3 -m tortillas -S ./sweb

      - name: Adding markdown
        if: always()
        run: cat /tmp/sweb/tortillas_summary.md >> $GITHUB_STEP_SUMMARY

  panic:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout Sweb
        uses: actions/checkout@v3
        with:
          repository: IAIK/sweb
          path: sweb

      - name: Install dependencies
        run: |
          sudo apt install -y qemu-utils qemu-system-x86 python3-yaml

      - name: Setup sweb
        run: |
          ./setup_sweb.sh $(pwd) $(pwd)/sweb panic

      - name: Run tortillas
        run: |
          ! python3 -m tortillas -S ./sweb

      - name: Adding markdown
        if: always()
        run: cat /tmp/sweb/tortillas_summary.md >> $GITHUB_STEP_SUMMARY
