name: Internal tests CI

on:
  # Runs on Every Push
  push:
  # Runs on Pull Requests
  pull_request:
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout Sweb
        uses: actions/checkout@v3
        with:
          repository: IAIK/sweb
          path: sweb

      - name: Install dependencies
        run: |
          sudo apt install -y qemu-utils qemu-system-x86 python3-yaml python3-pytest

      - name: Setup sweb
        run:
          ./setup_sweb.sh $(pwd) $(pwd)/sweb base

      - name: Run tortillas
        run: |
          python3 -m tortillas -S ./sweb

      - name: Run tests
        run: |
          pytest
