name: Internal tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt install -y qemu-utils qemu-system-x86 python3-yaml python3-pip
          pip install pytest

      - name: Setup and compile sweb
        run: |
          cmake -B"/tmp/sweb" -H"./example"
          cmake --build "/tmp/sweb" -j$(nproc)

      - name: Run tests
        run: |
          set -o pipefail
          echo -e '```\n' >> $GITHUB_STEP_SUMMARY
          pytest -s | tee -a $GITHUB_STEP_SUMMARY
          echo -e '```\n' >> $GITHUB_STEP_SUMMARY
